### ISSUE TITLE
Example how to use form-actions

### ISSUE THREAD

**Issue by nosovk** [ivanhofer/sveltekit-typescript-showcase#12]
https://kit.svelte.dev/docs/form-actions

**Comment by ivanhofer** [comment]
Not sure what you mean / what you miss. The form actions docs already show the example using TypeScript.

**Comment by nosovk** [comment]
I'm talking about this functionality: 
```typescript
use:enhance={({ form, data, action, cancel })
```

**Comment by ivanhofer** [comment]
But the `enahnce` function should already be typesafe. You get strongly typed arguments if you use it.

**Comment by nosovk** [comment]
but there is data in it, which should contain pageResponce, and it's not typed.

```typescript
    <form
      method="POST"
      action="/api/subscribe"
      use:enhance={({ form }) => {
        loading = true;

        return async ({ result }) => {
          errorText = '';
          if (result.type === 'failure') {
            errorText =
              result.data?.message;
          }
          loading = false;
          form.reset();
        };
      }}
    >
 ```

in example above `result.data` is not present in typings.

**Comment by ivanhofer** [comment]
Ah, now I see what you mean.
Unfortunately `SvelteKit` currently does not help us as much as it could. You need to manually type it like this:

![image](https://user-images.githubusercontent.com/21335119/221248260-f5b2b20a-5232-4ed3-8d54-e5187f41884d.png)

Then you will get all the properties present on the data object.
But you can't distinguish between the types of a successful and a failed response.
You would need to manually type the `Success` and `Invalid` types.

This is something where `SvelteKit` could provide better type definitions in the future. I will open an issue there.

**Comment by ivanhofer** [comment]
see here: https://github.com/sveltejs/kit/issues/7161

**Comment by ivanhofer** [comment]
And here is a PR: https://github.com/sveltejs/kit/pull/9201.
Once merged, you don't need to manually pass the generics.

**Comment by nosovk** [comment]
Thanks, it seems that it solves my issue for now. Unfortunately it was unclear from docs.

**Comment by mledl** [comment]
> And here is a PR: [sveltejs/kit#9201](https://github.com/sveltejs/kit/pull/9201). Once merged, you don't need to manually pass the generics.

This PR does not affect the default behaviour of the `ActionResult` type rather that renaming `Invalid` to `Failure`, right?

**Comment by ivanhofer** [comment]
`ActionResult` stays the same. But you will be able to import a strongly typed `SubmitFunction` from `./$types.js`
