### ISSUE TITLE
Question: Svelte breaking changes?

### ISSUE THREAD

**Issue by grnd-alt** [ivanhofer/sveltekit-typescript-showcase#15]
Hi first of all, thanks for your hard work on creating this helpful repo.

I am currently trying to implement your example of typed events in svelte. I am fairly Sure I've implemented it correctly, and setup typescript the right way. Anyways when trying to create a typed eventDispatcher, I get the standard Svelte "unexpected token, add lang='ts' to script tag" error. As visible in the image, other ts syntax works fine,just the createEventDispatcher part fails. Might it be some issue with vite?
![image](https://user-images.githubusercontent.com/56235737/236414278-9104142a-9874-4503-bf68-3d1aede73f5a.png)

**Comment by ivanhofer** [comment]
Did you use wrong quotes and `lang="ts"` fix the issue?
