### ISSUE TITLE
example about how to type functions exported from svelte components

### ISSUE THREAD

**Issue by opensas** [ivanhofer/sveltekit-typescript-showcase#3]
provide an example an explanation about how to type an exported function

Something like [this example](https://svelte.dev/repl/3727dbf69eb64625bd85a363f6f6c95b?version=3.38.2) from @tanhauhau 

```svelte
<script>
	let isOpen = true;
	let name = '';
	let email = '';
	
	export function openModal() {
		isOpen = true;
	}
	[...]
}
```

Right now, with ts, I get a `Property 'openModal' does not exist on type 'default'.ts(2339)`

**Comment by ivanhofer** [comment]
you need to tell `TypeScript` what type the component binding (`let dialog: Dialog`) should have:

_App.svelte_
```svelte
<script lang="ts">
   import Dialog from './Dialog.svelte'
   let dialog: Dialog
</script>

<Dialog bind:this={dialog} />

<button on:click={() => dialog.openModal() }>Open dialog</button>
```

_Dialog.svelte_
```svelte
<script lang="ts">
   let isOpen = true;

   export function openModal() {
      isOpen = true;
   }
</script>

<!-- markup -->
```
