### ISSUE TITLE
endpoint types and npm ci

### ISSUE THREAD

**Issue by cognominal** [ivanhofer/sveltekit-typescript-showcase#5]
I am trying to use the endpoint example.
Inspecting the source of svelte-kit It seems that to generate the types, one needs to run `npm ci`.
At least this the way I used to successfully generate the files.
It should probably mentioned.

I run into other mistakes. I have yet to need to read your doc to solve them.
I will keep you posted.

![image](https://user-images.githubusercontent.com/16176/174681286-81fc8f7e-74de-4168-9eff-ee006bcbeb35.png)

Thanks for your show case. It helps.

**Comment by thenbe** [comment]
Types are generated when you run either `svelte-kit dev` or `svelte-kit build`. Alternatively, you can just do `npx svelte-kit sync`.

More here: https://github.com/sveltejs/kit/issues/4165

**Comment by ivanhofer** [comment]
Thanks @ambiguous48 for your comment.

@cognominal I have updated the examples to mention this

**Comment by cognominal** [comment]
Thanks.
I don't know where is the script `svelte-kit` (not in my PATH)) but `npm run prepare` calls it allright to sync.

**Comment by cognominal** [comment]
Thx for your quick answer in 771811a7a1b4e3fdecf94690d02a5a14314c80bc

**Comment by ivanhofer** [comment]
Thanks for letting me know about the missing description! I hope that its now more clear how this process works
